---
title: "hw3"
author: "Hsiao"
date: "2021/6/5"
output: html_document
---

```{r}
# packages 
library("data.table") 
library("magrittr")
library("naniar")
library("plyr")
library("dplyr")
library("stringr")
library("ggplot2")
library("tidyr")
library("tibble")
```

```{r}
# import data 
load("/Users/Ano/Desktop/HRS_Chao/data_merge.RData")

```

```{r}
# first we use data from 2003 to learn the package "melt" and "reshape"
# the taking demo, adls, diseases from the data set 
library("data.table")
dt_03y <- data.table(df_c_03_YOUTH)
dt_03y <- dt_03y[, "survey_year":=2003]
# dt_03y <- dt_03y[,"rwstat":= NA]
# dt_03y <- dt_03y[,"worktype":= NA]
# dt_03y <- dt_03y[,"reduc":= NA]
# dt_03y <- dt_03y[,"rethnicty":= NA]
dt_03y <- dt_03y[,c("crt1","crt2"):= NA]
#dt_03y <- dt_03y[,c("othpres"):= NA]

demo_03y <-c("qtype","ser_no","survey_year","sex","c56","c57","crt1","crt2","type","area","a2","a5","a13","b1","b22","c1","e1","e2a","c12b","c12c","c26","c27","c28","c29")

# b15 -- ntothh ( omit partners and children), I encode b22 to includ all members living in this house
# c12c 從住院主因變成了最近一次住院是為什麼
# c26 cursomke ** 以前沒有的但我覺得蠻重要 99 96好像也有 可以考慮放
# c29 cursport ** 可考慮要不要放
# 有身高體重

which(colnames(dt_03y) =="c12b")
demo_dt_03y <- dt_03y[,c("qtype","ser_no","survey_year","sex","c56","c57","crt1","crt2","type","area","a2","a5","a13","b1","b22","c1","e1","e2a","c12b","c12c","c26","c27","c28","c29"),]
#ntothh exclude parners and childrens
# e6 is the work type
# 有身高體重了

demo_03y<- c("qtype","ser_no","survey_year","rsex","height","weight","crt1","crt2","dwell1","dwell2","reduc","ethnicty","marstat","nchldrn","ntothh","hlgenrat","rwstat","worktype","nomihosp","hosphp1","cursmoke","curdrink","curchew","frqsport")
demo_dt_03y<- setNames(demo_dt_03y, demo_03y)
#demo_dt_99 <- add_column(demo_dt_99,rage = NA , .after = "rsex" )
#-------------

#adls


phy_dt_03y <- dt_03y[,c("c231","c233","c234","c235","c236","c237","c239"),]


which(colnames(dt_03y) =="c246")
# phys like 站立15分鐘, 屈蹲, 雙手高舉到頭上, 扭轉東西, 拿重物, 跑步, 走兩三樓
phys_03y <- c("stand_15","crouch","hands_on_head","twist","carry_heavy","run","staris")
iadl_dt_03y <- dt_03y[,c("c241","c242","c243","c244","c245","c246","c24b","c24c"), ]
iadl_dt_03y <- add_column(iadl_dt_03y,dt_03y$c238, .after = "c243" )
iadl_03y <- c("grocery","financial","transport","walk200","heavywork","housework","telehphone","iadl_receive_help","iadl_who_help")


adls_dt_03y <- dt_03y[,c("c251","c252","c253","c254","c255","c256", "c25e")]
adls_03y <- c("bath","clothes","dine","wakeup","walk_indoor","WC","adl_who_help")
# general of ADLS is missing

names<- append(phys_03y,adls_03y)
names <- append(names,iadl_03y)
adls_dt_03y <- cbind(phy_dt_03y, adls_dt_03y, iadl_dt_03y)
adls_dt_03y<- setNames(adls_dt_03y, names)

#----------
# diseases 

#which(colnames(dt_96_y) =="f05c41"
dis_dt_03y <- dt_03y[,c("c3c1","c3c2","c3c3","c3b4","c3c5","c3c6","c3c7","c3c8","c3c9","c3_10","c3c11","c3c12","c3c13","c3c14","c3c15"),]
dis_03y <- c("hibp","diab","hrtpr","strok","cancer","broh","arth","ulcer","livpr","hipbone","catar","kiddi","gout","spur","osteo")
dis_dt_03y<- setNames(dis_dt_03y, dis_03y)
# 少了一些症狀，但是多問了跌倒狀況
# 跌倒狀況有包含有沒有頭部、頸部、脊椎骨折...
# 您“現在”還有這種病症嗎？


# spur = 骨刺(bone spur)
# arth = 關節炎(arthritis)
# catar = 白內障(cataract)
# glau = 青光眼(glaucoma)
# oteye = 其他眼疾
# asth = 氣喘(asthma)
# hibp = 高血壓(high blood pressure)
# hrtpr = 心臟問題( heart trouble)
# strok = 中風(stroke)
# cirpr = 血液循環不良(circulation problem)
# diab = 糖尿病(diabetes)
# thydi = 甲狀腺疾病(thyroid disease)
# hibc = 血油質高 (high blood ??)
# anem = 貧血(anemia)
# livpr = 肝膽疾病(liver, gallbladder)
# const = 便秘與痔瘡(constipation)
# ulcer = 胃潰瘍(ulcer)
# kiddi = 腎臟疾病(kidney)
# prost = 前列腺疾病(prostate)
# oturi = 其他泌尿科問題( other urine)
# skdis = 皮膚疾病( skin disease)
# neur = 腦神經問題(neuro)
# dizz = 暈眩(dizz)
# faint = 昏倒(faint)
# buzz = 耳鳴(buzz)
# brokbone = 骨折(broken bone)

#*belows are missing in 89
# cancer = 癌症(cancer) 
# broh = 支氣管炎(bronchitis) # !!replaceasth to broh
# tbc = 肺結核(tuberculosis)
# gout = 痛風(.)
# hipbone = 髖骨骨折( broken hipbone) ##老人嚴重死因之一
# headspine = 頭與脊椎外傷

#* New in 2003 
# osteo = osteoporosis 骨質疏鬆
```


```{r}
# fam 03y
# Now is their family members 
# Worker's intelligent 

#example 
d<- dt_03y[1:30, 1:30]


 for(i in 1:5){
  dt_03y[, paste0(i,"_livstat",  sep = ""):= 0]
  dt_03y[, paste0(i,"_livwhere", sep = ""):= 0]
  dt_03y[, paste0(i,"_meet",  sep= ""):=0]
  dt_03y[, paste0(i,"_tele",  sep="" ):=0]
 }


# question : can not call d$1_tele, but only d$"1_tele"
# can apply for the following 


# dt_03y <- dt_03y[, "1_livstat":=0] #living status =0 : living together
# dt_03y <- dt_03y[, "1_livwhere":=0] #living status =0 : living together
# dt_03y <- dt_03y[, "1_meet":=0] #living status =0 : living together
# dt_03y <- dt_03y[, "1_tele":=0] #living status =0 : living together
# dt_03y <- dt_03y[, "2_livstat":=0] #living status =0 : living together
# dt_03y <- dt_03y[, "2_livwhere":=0] #living status =0 : living together
# dt_03y <- dt_03y[, "2_meet":=0] #living status =0 : living together
# dt_03y <- dt_03y[, "2_tele":=0] #living status =0 : living together
# dt_03y <- dt_03y[, "3_livstat":=0] #living status =0 : living together
# dt_03y <- dt_03y[, "3_livwhere":=0] #living status =0 : living together
# dt_03y <- dt_03y[, "3_meet":=0] #living status =0 : living together
# dt_03y <- dt_03y[, "3_tele":=0] #living status =0 : living together
# dt_03y <- dt_03y[, "4_livstat":=0] #living status =0 : living together
# dt_03y <- dt_03y[, "4_livwhere":=0] #living status =0 : living together
# dt_03y <- dt_03y[, "4_meet":=0] #living status =0 : living together
# dt_03y <- dt_03y[, "4_tele":=0] #living status =0 : living together
# dt_03y <- dt_03y[, "5_livstat":=0] #living status =0 : living together
# dt_03y <- dt_03y[, "5_livwhere":=0] #living status =0 : living together
# dt_03y <- dt_03y[, "5_meet":=0] #living status =0 : living together
# dt_03y <- dt_03y[, "5_tele":=0] #living status =0 : living together

# 1~5 iving together (5)
# 6~12 living not together(7)
# 13~ 22 others (10)

 for(i in 13:22){
  dt_03y[, paste0(i,"_livstat", sep = ""):= 99]
  dt_03y[, paste0(i,"_livwhere", sep = ""):= 99]
  dt_03y[, paste0(i,"_meet", sep= ""):=99]
  dt_03y[, paste0(i,"_tele", sep="" ):=99]
 }

# dt_03y <- dt_03y[, "13_livstat":=99] #living status =99 : others
# dt_03y <- dt_03y[, "13_livwhere":=99] #living status =99 : others
# dt_03y <- dt_03y[, "13_meet":=99] #living status =99 : others
# dt_03y <- dt_03y[, "13_tele":=99] #living status =99 : others
# dt_03y <- dt_03y[, "14_livstat":=99] #living status =99 : others
# dt_03y <- dt_03y[, "14_livwhere":=99] #living status =99 : others
# dt_03y <- dt_03y[, "14_meet":=99] #living status =99 : others
# dt_03y <- dt_03y[, "14_tele":=99] #living status =99 : others
# dt_03y <- dt_03y[, "15_livstat":=99] #living status =99 : others
# dt_03y <- dt_03y[, "15_livwhere":=99] #living status =99 : others
# dt_03y <- dt_03y[, "15_meet":=99] #living status =99 : others
# dt_03y <- dt_03y[, "15_tele":=99] #living status =99 : others
# dt_03y <- dt_03y[, "16_livstat":=99] #living status =99 : others
# dt_03y <- dt_03y[, "16_livwhere":=99] #living status =99 : others
# dt_03y <- dt_03y[, "16_meet":=99] #living status =99 : others
# dt_03y <- dt_03y[, "16_tele":=99] #living status =99 : others
# dt_03y <- dt_03y[, "17_livstat":=99] #living status =99 : others
# dt_03y <- dt_03y[, "17_livwhere":=99] #living status =99 : others
# dt_03y <- dt_03y[, "17_meet":=99] #living status =99 : others
# dt_03y <- dt_03y[, "17_tele":=99] #living status =99 : others
# dt_03y <- dt_03y[, "18_livstat":=99] #living status =99 : others
# dt_03y <- dt_03y[, "18_livwhere":=99] #living status =99 : others
# dt_03y <- dt_03y[, "18_meet":=99] #living status =99 : others
# dt_03y <- dt_03y[, "18_tele":=99] #living status =99 : others
# dt_03y <- dt_03y[, "19_livstat":=99] #living status =99 : others
# dt_03y <- dt_03y[, "19_livwhere":=99] #living status =99 : others
# dt_03y <- dt_03y[, "19_meet":=99] #living status =99 : others
# dt_03y <- dt_03y[, "19_tele":=99] #living status =99 : others
# dt_03y <- dt_03y[, "20_livstat":=99] #living status =99 : others
# dt_03y <- dt_03y[, "20_livwhere":=99] #living status =99 : others
# dt_03y <- dt_03y[, "20_meet":=99] #living status =99 : others
# dt_03y <- dt_03y[, "20_tele":=99] #living status =99 : others
# dt_03y <- dt_03y[, "21_livstat":=99] #living status =99 : others
# dt_03y <- dt_03y[, "21_livwhere":=99] #living status =99 : others
# dt_03y <- dt_03y[, "21_meet":=99] #living status =99 : others
# dt_03y <- dt_03y[, "21_tele":=99] #living status =99 : others
# dt_03y <- dt_03y[, "22_livstat":=99] #living status =99 : others
# dt_03y <- dt_03y[, "22_livwhere":=99] #living status =99 : others
# dt_03y <- dt_03y[, "22_meet":=99] #living status =99 : others
# dt_03y <- dt_03y[, "22_tele":=99] #living status =99 : others
dt_03y <- dt_03y[, "survey_year":=2003]

for (i in 1:30){
 if(i %in% c(1:5)){setnames(d, i, paste(paste0("b", i, "01"), collapse = ', '))}
  else if (i %in% c(6:10)){setnames(d, i, paste(paste0("b", i-5, "02"), collapse = ', '))}
  else if (i %in% c(11:15)){setnames(d, i, paste(paste0("b", i-10, "03"), collapse = ', '))}
  else if (i %in% c(16:20)){setnames(d, i, paste(paste0("b", i-15, "04"), collapse = ', '))}
  else if (i %in% c(21:25)){setnames(d, i, paste(paste0("b", i-20, "05"), collapse = ', '))}
  else if (i %in% c(26:30)){setnames(d, i, paste(paste0("b", i-25, "06"), collapse = ', '))}
}
 for(i in 1:5){
  d[, paste0("livstat_", i, sep = ""):= 0]
  d[, paste0("livwhere_",i, sep = ""):= 0]
  d[, paste0("meet_", i, sep= ""):=0]
  d[, paste0("tele_", i, sep="" ):=0]
 }

dd<-d
print(cols)
dd<- dd[, .SD, .SDcols=cols  ]
##### 解決, 用這東西做



# for( i in 1:5){ cols<-c(paste0("b", seq(from=50, to =100, by=10 ), i), paste0(live,i) )}
# for( i in 11:17){ cols<-paste(cols, c(paste0("b", seq(from=5, to =14, by=1 ), i)))}
#for( i in 1:9){ cols<-paste(cols, c(paste0("b", seq(from=160, to =210, by=10 ), i), paste0(live,i+12)) )}
# for( i in 10){ cols<-paste(cols, c(paste0("b", seq(from=16, to =21, by=1 ), i), paste0(live,i+12)) )}

```

## 比起先取再rename, 我覺得好像先rename再取比較好 ##




```{r}

#set names
status <- c("_relation", "_sex", "_age", "_edu", "_work", "_marstat")
status2 <- c("_relation", "_sex", "_age", "_edu", "_work", "_marstat", "_livstat", "_livwhere", "_meet","_tele")
for(i in 1:5){
 setnames(dt_03y, paste0( "b", seq(from=50 ,to =100, by=10), i), paste0(i ,status))
}
for(i in 11:17){
 setnames(dt_03y, paste0( "b", 5:14, i), paste0(i-5 ,status2))
}
for(i in 1:9){
 setnames(dt_03y, paste0( "b", seq(from=160 ,to =210, by=10), i), paste0(i+12 ,status))
}
setnames(dt_03y, paste0("b", 16:21, 10), paste0(22, status))


# 取出

status2 <- c("_relation", "_sex", "_age", "_edu", "_work", "_marstat", "_livstat", "_livwhere", "_meet","_tele")

sapply()
paste0(1:22, status2)

cols <- do.call(paste0, expand.grid(1:22, status2))
# 可能要用regex 做ordering
# another approach 
# 用外積做

cols<- outer(1:22,status2, FUN = "paste0")
cols<- t(cols) # 做一個transpose
dim(cols) <- NULL # 降維
print(cols)


for(i in 1:5){ x<-paste0(i, status2)}

# 回傳東西會很麻煩
# lapply, 才會回傳東西給我 （憑鐔運算比較喎）
# 


fam_dt_03y <- dt_03y[, .SD , .SDcol = cols]

dt_03y <- cbind(demo_dt_03y, adls_dt_03y, dis_dt_03y,fam_dt_03y)

# added : iadl_receive_help, iadl_who_help, adls_who_help
dt_03y[, iadl_who_help := ifelse( dt_03y$iadl_receive_help ==0, 0, iadl_who_help)] 
# who_help =0 if nobody helps him/ her
dt_03y [, iadl_receive_help := NULL, ]


```


```{r}
# try
live<- c("_livstat", "_livwhere", "_meet", "_tele")
# four rules
cols<- do.call(paste0, expand.grid("b",seq(from=50, to =100, by=10 ) , 1:5))
cols <- append(cols, do.call(paste0, expand.grid(c(1:5, 13:22), live)))
cols <- append(cols, do.call(paste0, expand.grid("b",5:14, 11:17)))
cols <- append(cols, do.call(paste0, expand.grid("b",seq(from=160, to=210, by=10), 1:9)))
cols <- append(cols, do.call(paste0, expand.grid("b",seq(from=16, to=21, by=1),10)))
fam_dt_03y<- dt_03y [, .SD, .SDcols=cols  ]


x<- do.call(paste0, expand.grid(c("a","b","c","d","e"), 110:115, live))
x<- t(x)


# fam_dt_03y <- dt_03y[ , c(paste0("b", 5:10, "01"), paste0(live,"1"), paste0("b", 5:10, "02"), paste0(live,"2"), paste0("b", 5:10, "03"), paste0(live,"3"),paste0("b", 5:10, "04"), paste0(live,"4"), paste0("b", 5:10, "05"), paste0(live,"5"), paste0("b", 5:14, "11"), paste0("b", 5:14, "12"), paste0("b", 5:14, "13"), paste0("b", 5:14, "14"), paste0("b", 5:14, "15"), paste0("b", 5:14, "16"), paste0("b", 5:14, "17"), paste0("b", 16:21, "01"), paste0(live,"13"),paste0("b", 16:21, "02"), paste0(live,"14"),paste0("b", 16:21, "03"), paste0(live,"15"),paste0("b", 16:21, "04"), paste0(live,"16"), paste0("b", 16:21, "05"), paste0(live,"17"),paste0("b", 16:21, "06"), paste0(live,"18"),paste0("b", 16:21, "07"), paste0(live,"19"),paste0("b", 16:21, "08"), paste0(live,"20"),paste0("b", 16:21, "09"), paste0(live,"21"),paste0("b", 16:21, "10"), paste0(live,"22")),  ]


# cols2<- c("b501","b601","b701","b801","b901","b1001","1_livstat","1_livwhere","1_meet","1_tele","b502","b602","b702","b802","b902","b1002","2_livstat","2_livwhere","2_meet","2_tele","b503","b603","b703","b803","b903","b1003","3_livstat","3_livwhere","3_meet","3_tele","b504","b604","b704","b804","b904","b1004","4_livstat","4_livwhere","4_meet","4_tele","b505","b605","b705","b805","b905","b1005","5_livstat","5_livwhere","5_meet","5_tele","b511","b611","b711","b811","b911","b1011","b1111","b1211","b1311","b1411","b512","b612","b712","b812","b912","b1012","b1112","b1212","b1312","b1412","b513","b613","b713","b813","b913","b1013","b1113","b1213","b1313","b1413","b514","b614","b714","b814","b914","b1014","b1114","b1214","b1314","b1414","b515","b615","b715","b815","b915","b1015","b1115","b1215","b1315","b1415","b516","b616","b716","b816","b916","b1016","b1116","b1216","b1316","b1416","b517","b617","b717","b817","b917","b1017","b1117","b1217","b1317","b1417","b1601","b1701","b1801","b1901","b2001","b2101","13_livstat","13_livwhere","13_meet","13_tele","b1602","b1702","b1802","b1902","b2002","b2102","14_livstat","14_livwhere","14_meet","14_tele","b1603","b1703","b1803","b1903","b2003","b2103","15_livstat","15_livwhere","15_meet","15_tele","b1604","b1704","b1804","b1904","b2004","b2104","16_livstat","16_livwhere","16_meet","16_tele","b1605","b1705","b1805","b1905","b2005","b2105","17_livstat","17_livwhere","17_meet","17_tele","b1606","b1706","b1806","b1906","b2006","b2106","b1607","18_livstat","18_livwhere","18_meet","18_tele","b1707","b1807","b1907","b2007","b2107","19_livstat","19_livwhere","19_meet","19_tele","b1608","b1708","b1808","b1908","b2008","b2108","20_livstat","20_livwhere","20_meet","20_tele","b1609","b1709","b1809","b1909","b2009","b2109","21_livstat","21_livwhere","21_meet","21_tele","b1610","b1710","b1810","b1910","b2010","b2110","22_livstat","22_livwhere","22_meet","22_tele")


# fam_dt_03y <- dt_03y[,c("b501","b601","b701","b801","b901","b1001","1_livstat","1_livwhere","1_meet","1_tele","b502","b602","b702","b802","b902","b1002","2_livstat","2_livwhere","2_meet","2_tele","b503","b603","b703","b803","b903","b1003","3_livstat","3_livwhere","3_meet","3_tele","b504","b604","b704","b804","b904","b1004","4_livstat","4_livwhere","4_meet","4_tele","b505","b605","b705","b805","b905","b1005","5_livstat","5_livwhere","5_meet","5_tele","b511","b611","b711","b811","b911","b1011","b1111","b1211","b1311","b1411","b512","b612","b712","b812","b912","b1012","b1112","b1212","b1312","b1412","b513","b613","b713","b813","b913","b1013","b1113","b1213","b1313","b1413","b514","b614","b714","b814","b914","b1014","b1114","b1214","b1314","b1414","b515","b615","b715","b815","b915","b1015","b1115","b1215","b1315","b1415","b516","b616","b716","b816","b916","b1016","b1116","b1216","b1316","b1416","b517","b617","b717","b817","b917","b1017","b1117","b1217","b1317","b1417","b1601","b1701","b1801","b1901","b2001","b2101","13_livstat","13_livwhere","13_meet","13_tele","b1602","b1702","b1802","b1902","b2002","b2102","14_livstat","14_livwhere","14_meet","14_tele","b1603","b1703","b1803","b1903","b2003","b2103","15_livstat","15_livwhere","15_meet","15_tele","b1604","b1704","b1804","b1904","b2004","b2104","16_livstat","16_livwhere","16_meet","16_tele","b1605","b1705","b1805","b1905","b2005","b2105","17_livstat","17_livwhere","17_meet","17_tele","b1606","b1706","b1806","b1906","b2006","b2106","b1606","18_livstat","18_livwhere","18_meet","18_tele","b1707","b1807","b1907","b2007","b2107","19_livstat","19_livwhere","19_meet","19_tele","b1608","b1708","b1808","b1908","b2008","b2108","20_livstat","20_livwhere","20_meet","20_tele","b1609","b1709","b1809","b1909","b2009","b2109","21_livstat","21_livwhere","21_meet","21_tele","b1610","b1710","b1810","b1910","b2010","b2110","22_livstat","22_livwhere","22_meet","22_tele"),]

# paste(paste0("b", 5:22, "01"), collapse = ', ')


# b_01 -> living together
# b_11 -> not living togther

status <- c("_relation", "_sex", "_age", "_edu", "_work", "_marstat", "_livstat", "_livwhere", "_meet","_tele")

fam_03y<- outer(1:22,status, FUN = "paste0")
fam_03y<- t(fam_03y)
dim(fam_03y) <- NULL
fam_03y

# fam_03y <- c("1_relation","1_sex","1_age","1_edu","1_work","1_marstat","1_livstat","1_livwhere","1_meet","1_tele","2_relation","2_sex","2_age","2_edu","2_work","2_marstat","2_livstat","2_livwhere","2_meet","2_tele","3_relation","3_sex","3_age","3_edu","3_work","3_marstat","3_livstat","3_livwhere","3_meet","3_tele","4_relation","4_sex","4_age","4_edu","4_work","4_marstat","4_livstat","4_livwhere","4_meet","4_tele","5_relation","5_sex","5_age","5_edu","5_work","5_marstat","5_livstat","5_livwhere","5_meet","5_tele","6_relation","6_sex","6_age","6_edu","6_work","6_marstat","6_livstat","6_livwhere","6_meet","6_tele","7_relation","7_sex","7_age","7_edu","7_work","7_marstat","7_livstat","7_livwhere","7_meet","7_tele","8_relation","8_sex","8_age","8_edu","8_work","8_marstat","8_livstat","8_livwhere","8_meet","8_tele","9_relation","9_sex","9_age","9_edu","9_work","9_marstat","9_livstat","9_livwhere","9_meet","9_tele","10_relation","10_sex","10_age","10_edu","10_work","10_marstat","10_livstat","10_livwhere","10_meet","10_tele","11_relation","11_sex","11_age","11_edu","11_work","11_marstat","11_livstat","11_livwhere","11_meet","11_tele","12_relation","12_sex","12_age","12_edu","12_work","12_marstat","12_livstat","12_livwhere","12_meet","12_tele","13_relation","13_sex","13_age","13_edu","13_work","13_marstat","13_livstat","13_livwhere","13_meet","13_tele","14_relation","14_sex","14_age","14_edu","14_work","14_marstat","14_livstat","14_livwhere","14_meet","14_tele","15_relation","15_sex","15_age","15_edu","15_work","15_marstat","15_livstat","15_livwhere","15_meet","15_tele","16_relation","16_sex","16_age","16_edu","16_work","16_marstat","16_livstat","16_livwhere","16_meet","16_tele","17_relation","17_sex","17_age","17_edu","17_work","17_marstat","17_livstat","17_livwhere","17_meet","17_tele","18_relation","18_sex","18_age","18_edu","18_work","18_marstat","18_livstat","18_livwhere","18_meet","18_tele","19_relation","19_sex","19_age","19_edu","19_work","19_marstat","19_livstat","19_livwhere","19_meet","19_tele","20_relation","20_sex","20_age","20_edu","20_work","20_marstat","20_livstat","20_livwhere","20_meet","20_tele","21_relation","21_sex","21_age","21_edu","21_work","21_marstat","21_livstat","21_livwhere","21_meet","21_tele","22_relation","22_sex","22_age","22_edu","22_work","22_marstat","22_livstat","22_livwhere","22_meet","22_tele")

fam_dt_03y<- setNames(fam_dt_03y, fam_03y)
# family members done here

# merge for the final dataset 
dt_03y <- cbind(demo_dt_03y, adls_dt_03y, dis_dt_03y,fam_dt_03y)

# added : iadl_receive_help, iadl_who_help, adls_who_help
dt_03y[, iadl_who_help := ifelse( dt_03y$iadl_receive_help ==0, 0, iadl_who_help)] 
# who_help =0 if nobody helps him/ her
dt_03y [, iadl_receive_help := NULL, ]
```


```{r}
# 03o

dt_03o <- data.table(df_c_03_ELDER)
dt_03o <- dt_03o[, "survey_year":=2003]

cols<-c("rwstat","worktype","reduc","rethnicty","crt1","crt2","othpres")
dt_03o <- dt_03o[, cols := NA]
# dt_03o <- dt_03o[,"rwstat":= NA]
# dt_03o <- dt_03o[,"worktype":= NA]
# dt_03o <- dt_03o[,"reduc":= NA]
# dt_03o <- dt_03o[,"rethnicty":= NA]
# dt_03o <- dt_03o[,c("crt1","crt2"):= NA]
# dt_03o <- dt_03o[,c("othpres"):= NA]

demo_03o <-c("qtype","ser_no","survey_year","sex","crt1","crt2","type","area","reduc","rethnicty","a192","b1_1","b22","c1","rwstat","worktype","c12b","c12c","c26","c27","c28","c29")

# b15 -- ntothh ( omit partners and children), I encode b22 to includ all members living in this house
# c12c 從住院主因變成了最近一次住院是為什麼
# c26 cursomke ** 以前沒有的但我覺得蠻重要 99 96好像也有 可以考慮放
# c29 cursport ** 可考慮要不要放

demo_dt_03o <- dt_03o[,c("qtype","ser_no","survey_year","sex","crt1","crt2","type","area","reduc","rethnicty","a192","b1_1","b22","c1","rwstat","worktype","c12b","c12c","c26","c27","c28","c29"),]
#ntothh exclude parners and childrens
# e6 is the work type
# 有身高體重了

demo_03o<- c("qtype","ser_no","survey_year","rsex","crt1","crt2","dwell1","dwell2","reduc","ethnicty","marstat","nchldrn","ntothh","hlgenrat","rwstat","worktype","nomihosp","hosphp1","cursmoke","curdrink","curchew","frqsport")
demo_dt_03o<- setNames(demo_dt_03o, demo_03o)
#demo_dt_99 <- add_column(demo_dt_99,rage = NA , .after = "rsex" )
#-------------

#adls


phy_dt_03o <- dt_03o[,c("c231","c233","c234","c235","c236","c237","c239"),]


which(colnames(dt_03o) =="c246")
which(colnames(dt_03o) =="c232")
# phys like 站立15分鐘, 屈蹲, 雙手高舉到頭上, 扭轉東西, 拿重物, 跑步, 走兩三樓
phys_03o <- c("stand_15","crouch","hands_on_head","twist","carry_heavy","run","staris")
iadl_dt_03o <- dt_03o[,c("c241","c242","c243","c244","c245","c246","c24b","c24c"), ]
iadl_dt_03o <- add_column(iadl_dt_03o,dt_03o$c238, .after = "c243" )
iadl_03o <- c("grocery","financial","transport","walk200","heavywork","housework","telehphone","iadl_receive_help","iadl_who_help")

adls_dt_03o <- dt_03o[,c("c251","c252","c253","c254","c255","c256", "c25e")]
adls_03o <- c("bath","clothes","dine","wakeup","walk_indoor","WC","adl_who_help")
# general of ADLS is missing

names<- append(phys_03o,adls_03o)
names <- append(names,iadl_03o)
adls_dt_03o <- cbind(phy_dt_03o, adls_dt_03o, iadl_dt_03o)
adls_dt_03o<- setNames(adls_dt_03o, names)

#----------
# diseases 

dis_dt_03o <- dt_03o[,c("c3c1","c3c2","c3c3","c3b4","c3c5","c3c6","c3c7","c3c8","c3c9","c3_10","c3c11","c3c12","c3c13","c3c14","c3c15"),]
dis_03o <- c("hibp","diab","hrtpr","strok","cancer","broh","arth","ulcer","livpr","hipbone","catar","kiddi","gout","spur","osteo")
dis_dt_03o<- setNames(dis_dt_03o, dis_03o)



# dt_03o <- cbind(demo_dt_03o, adls_dt_03o, dis_dt_03o)

```

```{r}
 for(i in 1:5){
  dt_03o[, paste0(i,"_livstat", sep = ""):= 0]
  dt_03o[, paste0(i,"_livwhere", sep = ""):= 0]
  dt_03o[, paste0(i,"_meet", sep= ""):=0]
  dt_03o[, paste0(i,"_tele", sep="" ):=0]
 }

 for(i in 13:22){
  dt_03o[, paste0(i,"_livstat", sep = ""):= 99]
  dt_03o[, paste0(i,"_livwhere", sep = ""):= 99]
  dt_03o[, paste0(i,"_meet", sep= ""):=99]
  dt_03o[, paste0(i,"_tele", sep="" ):=99]
 }

# fam 03o
# dt_03o <- dt_03o[, "1_livstat":=0] #living status =0 : living together
# dt_03o <- dt_03o[, "1_livwhere":=0] #living status =0 : living together
# dt_03o <- dt_03o[, "1_meet":=0] #living status =0 : living together
# dt_03o <- dt_03o[, "1_tele":=0] #living status =0 : living together
# dt_03o <- dt_03o[, "2_livstat":=0] #living status =0 : living together
# dt_03o <- dt_03o[, "2_livwhere":=0] #living status =0 : living together
# dt_03o <- dt_03o[, "2_meet":=0] #living status =0 : living together
# dt_03o <- dt_03o[, "2_tele":=0] #living status =0 : living together
# dt_03o <- dt_03o[, "3_livstat":=0] #living status =0 : living together
# dt_03o <- dt_03o[, "3_livwhere":=0] #living status =0 : living together
# dt_03o <- dt_03o[, "3_meet":=0] #living status =0 : living together
# dt_03o <- dt_03o[, "3_tele":=0] #living status =0 : living together
# dt_03o <- dt_03o[, "4_livstat":=0] #living status =0 : living together
# dt_03o <- dt_03o[, "4_livwhere":=0] #living status =0 : living together
# dt_03o <- dt_03o[, "4_meet":=0] #living status =0 : living together
# dt_03o <- dt_03o[, "4_tele":=0] #living status =0 : living together
# dt_03o <- dt_03o[, "5_livstat":=0] #living status =0 : living together
# dt_03o <- dt_03o[, "5_livwhere":=0] #living status =0 : living together
# dt_03o <- dt_03o[, "5_meet":=0] #living status =0 : living together
# dt_03o <- dt_03o[, "5_tele":=0] #living status =0 : living together

# 1~5 iving together (5)
# 6~12 living not together(7)
# 13~ 22 others (10)
# dt_03o <- dt_03o[, "13_livstat":=99] #living status =99 : others
# dt_03o <- dt_03o[, "13_livwhere":=99] #living status =99 : others
# dt_03o <- dt_03o[, "13_meet":=99] #living status =99 : others
# dt_03o <- dt_03o[, "13_tele":=99] #living status =99 : others
# dt_03o <- dt_03o[, "14_livstat":=99] #living status =99 : others
# dt_03o <- dt_03o[, "14_livwhere":=99] #living status =99 : others
# dt_03o <- dt_03o[, "14_meet":=99] #living status =99 : others
# dt_03o <- dt_03o[, "14_tele":=99] #living status =99 : others
# dt_03o <- dt_03o[, "15_livstat":=99] #living status =99 : others
# dt_03o <- dt_03o[, "15_livwhere":=99] #living status =99 : others
# dt_03o <- dt_03o[, "15_meet":=99] #living status =99 : others
# dt_03o <- dt_03o[, "15_tele":=99] #living status =99 : others
# dt_03o <- dt_03o[, "16_livstat":=99] #living status =99 : others
# dt_03o <- dt_03o[, "16_livwhere":=99] #living status =99 : others
# dt_03o <- dt_03o[, "16_meet":=99] #living status =99 : others
# dt_03o <- dt_03o[, "16_tele":=99] #living status =99 : others
# dt_03o <- dt_03o[, "17_livstat":=99] #living status =99 : others
# dt_03o <- dt_03o[, "17_livwhere":=99] #living status =99 : others
# dt_03o <- dt_03o[, "17_meet":=99] #living status =99 : others
# dt_03o <- dt_03o[, "17_tele":=99] #living status =99 : others
# dt_03o <- dt_03o[, "18_livstat":=99] #living status =99 : others
# dt_03o <- dt_03o[, "18_livwhere":=99] #living status =99 : others
# dt_03o <- dt_03o[, "18_meet":=99] #living status =99 : others
# dt_03o <- dt_03o[, "18_tele":=99] #living status =99 : others
# dt_03o <- dt_03o[, "19_livstat":=99] #living status =99 : others
# dt_03o <- dt_03o[, "19_livwhere":=99] #living status =99 : others
# dt_03o <- dt_03o[, "19_meet":=99] #living status =99 : others
# dt_03o <- dt_03o[, "19_tele":=99] #living status =99 : others
# dt_03o <- dt_03o[, "20_livstat":=99] #living status =99 : others
# dt_03o <- dt_03o[, "20_livwhere":=99] #living status =99 : others
# dt_03o <- dt_03o[, "20_meet":=99] #living status =99 : others
# dt_03o <- dt_03o[, "20_tele":=99] #living status =99 : others
# dt_03o <- dt_03o[, "21_livstat":=99] #living status =99 : others
# dt_03o <- dt_03o[, "21_livwhere":=99] #living status =99 : others
# dt_03o <- dt_03o[, "21_meet":=99] #living status =99 : others
# dt_03o <- dt_03o[, "21_tele":=99] #living status =99 : others
# dt_03o <- dt_03o[, "22_livstat":=99] #living status =99 : others
# dt_03o <- dt_03o[, "22_livwhere":=99] #living status =99 : others
# dt_03o <- dt_03o[, "22_meet":=99] #living status =99 : others
# dt_03o <- dt_03o[, "22_tele":=99] #living status =99 : others


                
fam_dt_03o <- dt_03o[,c("b501","b601","b701","b801","b901","b1001","1_livstat","1_livwhere","1_meet","1_tele","b502","b602","b702","b802","b902","b1002","2_livstat","2_livwhere","2_meet","2_tele","b503","b603","b703","b803","b903","b1003","3_livstat","3_livwhere","3_meet","3_tele","b504","b604","b704","b804","b904","b1004","4_livstat","4_livwhere","4_meet","4_tele","b505","b605","b705","b805","b905","b1005","5_livstat","5_livwhere","5_meet","5_tele","b511","b611","b711","b811","b911","b1011","b1111","b1211","b1311","b1411","b512","b612","b712","b812","b912","b1012","b1112","b1212","b1312","b1412","b513","b613","b713","b813","b913","b1013","b1113","b1213","b1313","b1413","b514","b614","b714","b814","b914","b1014","b1114","b1214","b1314","b1414","b515","b615","b715","b815","b915","b1015","b1115","b1215","b1315","b1415","b516","b616","b716","b816","b916","b1016","b1116","b1216","b1316","b1416","b516","b617","b717","b817","b917","b1017","b1117","b1217","b1317","b1417","b1601","b1701","b1801","b1901","b2001","b2101","13_livstat","13_livwhere","13_meet","13_tele","b1602","b1702","b1802","b1902","b2002","b2102","14_livstat","14_livwhere","14_meet","14_tele","b1603","b1703","b1803","b1903","b2003","b2103","15_livstat","15_livwhere","15_meet","15_tele","b1604","b1704","b1804","b1904","b2004","b2104","16_livstat","16_livwhere","16_meet","16_tele","b1605","b1705","b1805","b1905","b2005","b2105","17_livstat","17_livwhere","17_meet","17_tele","b1606","b1706","b1806","b1906","b2006","b2106","b1606","18_livstat","18_livwhere","18_meet","18_tele","b1707","b1807","b1907","b2007","b2107","19_livstat","19_livwhere","19_meet","19_tele","b1608","b1708","b1808","b1908","b2008","b2108","20_livstat","20_livwhere","20_meet","20_tele","b1609","b1709","b1809","b1909","b2009","b2109","21_livstat","21_livwhere","21_meet","21_tele","b1610","b1710","b1810","b1910","b2010","b2110","22_livstat","22_livwhere","22_meet","22_tele","b518","b618","b718","b818","b918","b1018","b1118","b1218","b1318","b1418","b519","b619","b719","b819","b919","b1019","b1119","b1219","b1319","b1419","b520","b620","b720","b820","b920","b1020","b1120","b1220","b1320","b1420","b521","b621","b721","b821","b921","b1021","b1121","b1221","b1321","b1421"),]
# other 11, other12 are grandchildren -> omit
# b518 : people23 to 26 : 18, 19, 20 ,21  不同住

which(colnames(dt_03o) =="b1121")
summary(dt_03o$b518) # if 88 then NAs

fam_03o <- c("1_relation","1_sex","1_age","1_edu","1_work","1_marstat","1_livstat","1_livwhere","1_meet","1_tele","2_relation","2_sex","2_age","2_edu","2_work","2_marstat","2_livstat","2_livwhere","2_meet","2_tele","3_relation","3_sex","3_age","3_edu","3_work","3_marstat","3_livstat","3_livwhere","3_meet","3_tele","4_relation","4_sex","4_age","4_edu","4_work","4_marstat","4_livstat","4_livwhere","4_meet","4_tele","5_relation","5_sex","5_age","5_edu","5_work","5_marstat","5_livstat","5_livwhere","5_meet","5_tele","6_relation","6_sex","6_age","6_edu","6_work","6_marstat","6_livstat","6_livwhere","6_meet","6_tele","7_relation","7_sex","7_age","7_edu","7_work","7_marstat","7_livstat","7_livwhere","7_meet","7_tele","8_relation","8_sex","8_age","8_edu","8_work","8_marstat","8_livstat","8_livwhere","8_meet","8_tele","9_relation","9_sex","9_age","9_edu","9_work","9_marstat","9_livstat","9_livwhere","9_meet","9_tele","10_relation","10_sex","10_age","10_edu","10_work","10_marstat","10_livstat","10_livwhere","10_meet","10_tele","11_relation","11_sex","11_age","11_edu","11_work","11_marstat","11_livstat","11_livwhere","11_meet","11_tele","12_relation","12_sex","12_age","12_edu","12_work","12_marstat","12_livstat","12_livwhere","12_meet","12_tele","13_relation","13_sex","13_age","13_edu","13_work","13_marstat","13_livstat","13_livwhere","13_meet","13_tele","14_relation","14_sex","14_age","14_edu","14_work","14_marstat","14_livstat","14_livwhere","14_meet","14_tele","15_relation","15_sex","15_age","15_edu","15_work","15_marstat","15_livstat","15_livwhere","15_meet","15_tele","16_relation","16_sex","16_age","16_edu","16_work","16_marstat","16_livstat","16_livwhere","16_meet","16_tele","17_relation","17_sex","17_age","17_edu","17_work","17_marstat","17_livstat","17_livwhere","17_meet","17_tele","18_relation","18_sex","18_age","18_edu","18_work","18_marstat","18_livstat","18_livwhere","18_meet","18_tele","19_relation","19_sex","19_age","19_edu","19_work","19_marstat","19_livstat","19_livwhere","19_meet","19_tele","20_relation","20_sex","20_age","20_edu","20_work","20_marstat","20_livstat","20_livwhere","20_meet","20_tele","21_relation","21_sex","21_age","21_edu","21_work","21_marstat","21_livstat","21_livwhere","21_meet","21_tele","22_relation","22_sex","22_age","22_edu","22_work","22_marstat","22_livstat","22_livwhere","22_meet","22_tele","23_relation","23_sex","23_age","23_edu","23_work","23_marstat","23_livstat","23_livwhere","23_meet","23_tele","24_relation","24_sex","24_age","24_edu","24_work","24_marstat","24_livstat","24_livwhere","24_meet","24_tele","25_relation","25_sex","25_age","25_edu","25_work","25_marstat","25_livstat","25_livwhere","25_meet","25_tele","26_relation","26_sex","26_age","26_edu","26_work","26_marstat","26_livstat","26_livwhere","26_meet","26_tele")

fam_dt_03o<- setNames(fam_dt_03o, fam_03o)

dt_03o <- cbind(demo_dt_03o, adls_dt_03o, dis_dt_03y,fam_dt_03o)

# added : iadl_receive_help, iadl_who_help, adls_who_help
dt_03o[, iadl_who_help := ifelse( dt_03o$iadl_receive_help ==0, 0, iadl_who_help)] 
# who_help =0 if nobody helps him/ her
dt_03o[, iadl_receive_help := NULL, ]

summary(dt_03o$adl_who_help)

```

```{r}
library(reshape)
# Now I subset part of the data to learn how to use "reshape" and "melt"
# the meaning of the code refer to the code book of hw3
# idvar onlo incl. ser_no and adl_who_help 
# 2003 youth
liv<- c("_relation","_sex","_age","_edu","_work","_marstat","_livstat","_livwhere","_meet","_tele")

cols<- do.call(paste0, expand.grid(1:22, liv))
cols<- append(c("ser_no", "survey_year", "qtype","adl_who_help"), cols)

tt<- dt_03y[, .SD, .SDcols=cols ] 


test <- dt_03y[ ,c("ser_no","survey_year","qtype","adl_who_help","1_relation","1_sex","1_age","1_edu","1_work","1_marstat","1_livstat","1_livwhere","1_meet","1_tele","2_relation","2_sex","2_age","2_edu","2_work","2_marstat","2_livstat","2_livwhere","2_meet","2_tele","3_relation","3_sex","3_age","3_edu","3_work","3_marstat","3_livstat","3_livwhere","3_meet","3_tele","4_relation","4_sex","4_age","4_edu","4_work","4_marstat","4_livstat","4_livwhere","4_meet","4_tele","5_relation","5_sex","5_age","5_edu","5_work","5_marstat","5_livstat","5_livwhere","5_meet","5_tele","6_relation","6_sex","6_age","6_edu","6_work","6_marstat","6_livstat","6_livwhere","6_meet","6_tele","7_relation","7_sex","7_age","7_edu","7_work","7_marstat","7_livstat","7_livwhere","7_meet","7_tele","8_relation","8_sex","8_age","8_edu","8_work","8_marstat","8_livstat","8_livwhere","8_meet","8_tele","9_relation","9_sex","9_age","9_edu","9_work","9_marstat","9_livstat","9_livwhere","9_meet","9_tele","10_relation","10_sex","10_age","10_edu","10_work","10_marstat","10_livstat","10_livwhere","10_meet","10_tele","11_relation","11_sex","11_age","11_edu","11_work","11_marstat","11_livstat","11_livwhere","11_meet","11_tele","12_relation","12_sex","12_age","12_edu","12_work","12_marstat","12_livstat","12_livwhere","12_meet","12_tele","13_relation","13_sex","13_age","13_edu","13_work","13_marstat","13_livstat","13_livwhere","13_meet","13_tele","14_relation","14_sex","14_age","14_edu","14_work","14_marstat","14_livstat","14_livwhere","14_meet","14_tele","15_relation","15_sex","15_age","15_edu","15_work","15_marstat","15_livstat","15_livwhere","15_meet","15_tele","16_relation","16_sex","16_age","16_edu","16_work","16_marstat","16_livstat","16_livwhere","16_meet","16_tele","17_relation","17_sex","17_age","17_edu","17_work","17_marstat","17_livstat","17_livwhere","17_meet","17_tele","18_relation","18_sex","18_age","18_edu","18_work","18_marstat","18_livstat","18_livwhere","18_meet","18_tele","19_relation","19_sex","19_age","19_edu","19_work","19_marstat","19_livstat","19_livwhere","19_meet","19_tele","20_relation","20_sex","20_age","20_edu","20_work","20_marstat","20_livstat","20_livwhere","20_meet","20_tele","21_relation","21_sex","21_age","21_edu","21_work","21_marstat","21_livstat","21_livwhere","21_meet","21_tele","22_relation","22_sex","22_age","22_edu","22_work","22_marstat","22_livstat","22_livwhere","22_meet","22_tele"),]

#test<- test[,1:32]
x<- list( c(paste0(1:22, "_relation")), c(paste0(1:22, "_sex")), c(paste0(1:22, "_age")), c(paste0(1:22,"_edu")), c(paste0(1:22, "_work")), c(paste0(1:22, "_marstat")), c(paste0(1:22, "_livstat")), c(paste0(1:22, "_livwhere")), c(paste0(1:22, "_meet")), c(paste0(1:22, "_tele")))

xx<-  list( c("1_relation","2_relation","3_relation","4_relation","5_relation","6_relation","7_relation","8_relation","9_relation","10_relation","11_relation","12_relation","13_relation","14_relation","15_relation","16_relation","17_relation","18_relation","19_relation","20_relation","21_relation","22_relation"),c("1_sex","2_sex","3_sex","4_sex","5_sex","6_sex","7_sex","8_sex","9_sex","10_sex","11_sex","12_sex","13_sex","14_sex","15_sex","16_sex","17_sex","18_sex","19_sex","20_sex","21_sex","22_sex"),c("1_age","2_age","3_age","4_age","5_age","6_age","7_age","8_age","9_age","10_age","11_age","12_age","13_age","14_age","15_age","16_age","17_age","18_age","19_age","20_age","21_age","22_age"),c("1_edu","2_edu","3_edu","4_edu","5_edu","6_edu","7_edu","8_edu","9_edu","10_edu","11_edu","12_edu","13_edu","14_edu","15_edu","16_edu","17_edu","18_edu","19_edu","20_edu","21_edu","22_edu"),c("1_work","2_work","3_work","4_work","5_work","6_work","7_work","8_work","9_work","10_work","11_work","12_work","13_work","14_work","15_work","16_work","17_work","18_work","19_work","20_work","21_work","22_work"),c("1_marstat","2_marstat","3_marstat","4_marstat","5_marstat","6_marstat","7_marstat","8_marstat","9_marstat","10_marstat","11_marstat","12_marstat","13_marstat","14_marstat","15_marstat","16_marstat","17_marstat","18_marstat","19_marstat","20_marstat","21_marstat","22_marstat"),c("1_livstat","2_livstat","3_livstat","4_livstat","5_livstat","6_livstat","7_livstat","8_livstat","9_livstat","10_livstat","11_livstat","12_livstat","13_livstat","14_livstat","15_livstat","16_livstat","17_livstat","18_livstat","19_livstat","20_livstat","21_livstat","22_livstat"),c("1_livwhere","2_livwhere","3_livwhere","4_livwhere","5_livwhere","6_livwhere","7_livwhere","8_livwhere","9_livwhere","10_livwhere","11_livwhere","12_livwhere","13_livwhere","14_livwhere","15_livwhere","16_livwhere","17_livwhere","18_livwhere","19_livwhere","20_livwhere","21_livwhere","22_livwhere"),c("1_meet","2_meet","3_meet","4_meet","5_meet","6_meet","7_meet","8_meet","9_meet","10_meet","11_meet","12_meet","13_meet","14_meet","15_meet","16_meet","17_meet","18_meet","19_meet","20_meet","21_meet","22_meet"),c("1_tele","2_tele","3_tele","4_tele","5_tele","6_tele","7_tele","8_tele","9_tele","10_tele","11_tele","12_tele","13_tele","14_tele","15_tele","16_tele","17_tele","18_tele","19_tele","20_tele","21_tele","22_tele"))

dt_03y_reshape <- reshape(test, varying =x , direction = "long", timevar = "ID_i", idvar = c("ser_no","survey_year","qtype","adl_who_help") , v.names = c("relationship","sex","age","edu","work","marstat","livstat","livwhere","meet","tele"))


dt_03y_reshape[, "member_id":= paste0(qtype, "_", ser_no, "_", ID_i)]
# How can I do this in .SD

#try: dt_03y_reshape<-  dt_03y_reshape[, "m_id" := do.call(paste, c(.SD, sep="_"), SDcols = c(dt_03y_reshape$qtype, dt_03y_reshape$ser_no, dt_03y_reshape$ID_i)),]
setcolorder(dt_03y_reshape, "member_id")

```


```{r}
# 2003 old

liv<- c("_relation","_sex","_age","_edu","_work","_marstat","_livstat","_livwhere","_meet","_tele")

cols<- do.call(paste0, expand.grid(1:26, liv))
cols<- append(c("ser_no", "survey_year", "qtype","adl_who_help"), cols)

tt<- dt_03o[, .SD, .SDcols=cols ] 


#tt <- dt_03o[ ,c("ser_no","survey_year","qtype","adl_who_help","1_relation","1_sex","1_age","1_edu","1_work","1_marstat","1_livstat","1_livwhere","1_meet","1_tele","2_relation","2_sex","2_age","2_edu","2_work","2_marstat","2_livstat","2_livwhere","2_meet","2_tele","3_relation","3_sex","3_age","3_edu","3_work","3_marstat","3_livstat","3_livwhere","3_meet","3_tele","4_relation","4_sex","4_age","4_edu","4_work","4_marstat","4_livstat","4_livwhere","4_meet","4_tele","5_relation","5_sex","5_age","5_edu","5_work","5_marstat","5_livstat","5_livwhere","5_meet","5_tele","6_relation","6_sex","6_age","6_edu","6_work","6_marstat","6_livstat","6_livwhere","6_meet","6_tele","7_relation","7_sex","7_age","7_edu","7_work","7_marstat","7_livstat","7_livwhere","7_meet","7_tele","8_relation","8_sex","8_age","8_edu","8_work","8_marstat","8_livstat","8_livwhere","8_meet","8_tele","9_relation","9_sex","9_age","9_edu","9_work","9_marstat","9_livstat","9_livwhere","9_meet","9_tele","10_relation","10_sex","10_age","10_edu","10_work","10_marstat","10_livstat","10_livwhere","10_meet","10_tele","11_relation","11_sex","11_age","11_edu","11_work","11_marstat","11_livstat","11_livwhere","11_meet","11_tele","12_relation","12_sex","12_age","12_edu","12_work","12_marstat","12_livstat","12_livwhere","12_meet","12_tele","13_relation","13_sex","13_age","13_edu","13_work","13_marstat","13_livstat","13_livwhere","13_meet","13_tele","14_relation","14_sex","14_age","14_edu","14_work","14_marstat","14_livstat","14_livwhere","14_meet","14_tele","15_relation","15_sex","15_age","15_edu","15_work","15_marstat","15_livstat","15_livwhere","15_meet","15_tele","16_relation","16_sex","16_age","16_edu","16_work","16_marstat","16_livstat","16_livwhere","16_meet","16_tele","17_relation","17_sex","17_age","17_edu","17_work","17_marstat","17_livstat","17_livwhere","17_meet","17_tele","18_relation","18_sex","18_age","18_edu","18_work","18_marstat","18_livstat","18_livwhere","18_meet","18_tele","19_relation","19_sex","19_age","19_edu","19_work","19_marstat","19_livstat","19_livwhere","19_meet","19_tele","20_relation","20_sex","20_age","20_edu","20_work","20_marstat","20_livstat","20_livwhere","20_meet","20_tele","21_relation","21_sex","21_age","21_edu","21_work","21_marstat","21_livstat","21_livwhere","21_meet","21_tele","22_relation","22_sex","22_age","22_edu","22_work","22_marstat","22_livstat","22_livwhere","22_meet","22_tele","23_relation","23_sex","23_age","23_edu","23_work","23_marstat","23_livstat","23_livwhere","23_meet","23_tele","24_relation","24_sex","24_age","24_edu","24_work","24_marstat","24_livstat","24_livwhere","24_meet","24_tele","25_relation","25_sex","25_age","25_edu","25_work","25_marstat","25_livstat","25_livwhere","25_meet","25_tele","26_relation","26_sex","26_age","26_edu","26_work","26_marstat","26_livstat","26_livwhere","26_meet","26_tele"),]


x<- list( c(paste0(1:26, "_relation")), c(paste0(1:26, "_sex")), c(paste0(1:26, "_age")), c(paste0(1:26,"_edu")), c(paste0(1:26, "_work")), c(paste0(1:26, "_marstat")), c(paste0(1:26, "_livstat")), c(paste0(1:26, "_livwhere")), c(paste0(1:26, "_meet")), c(paste0(1:26, "_tele")))

#setdiff(x,xx)
#xx<-list( c("1_relation","2_relation","3_relation","4_relation","5_relation","6_relation","7_relation","8_relation","9_relation","10_relation","11_relation","12_relation","13_relation","14_relation","15_relation","16_relation","17_relation","18_relation","19_relation","20_relation","21_relation","22_relation","23_relation","24_relation","25_relation","26_relation"),c("1_sex","2_sex","3_sex","4_sex","5_sex","6_sex","7_sex","8_sex","9_sex","10_sex","11_sex","12_sex","13_sex","14_sex","15_sex","16_sex","17_sex","18_sex","19_sex","20_sex","21_sex","22_sex","23_sex","24_sex","25_sex","26_sex"),c("1_age","2_age","3_age","4_age","5_age","6_age","7_age","8_age","9_age","10_age","11_age","12_age","13_age","14_age","15_age","16_age","17_age","18_age","19_age","20_age","21_age","22_age","23_age","24_age","25_age","26_age"),c("1_edu","2_edu","3_edu","4_edu","5_edu","6_edu","7_edu","8_edu","9_edu","10_edu","11_edu","12_edu","13_edu","14_edu","15_edu","16_edu","17_edu","18_edu","19_edu","20_edu","21_edu","22_edu","23_edu","24_edu","25_edu","26_edu"),c("1_work","2_work","3_work","4_work","5_work","6_work","7_work","8_work","9_work","10_work","11_work","12_work","13_work","14_work","15_work","16_work","17_work","18_work","19_work","20_work","21_work","22_work","23_work","24_work","25_work","26_work"),c("1_marstat","2_marstat","3_marstat","4_marstat","5_marstat","6_marstat","7_marstat","8_marstat","9_marstat","10_marstat","11_marstat","12_marstat","13_marstat","14_marstat","15_marstat","16_marstat","17_marstat","18_marstat","19_marstat","20_marstat","21_marstat","22_marstat","23_marstat","24_marstat","25_marstat","26_marstat"),c("1_livstat","2_livstat","3_livstat","4_livstat","5_livstat","6_livstat","7_livstat","8_livstat","9_livstat","10_livstat","11_livstat","12_livstat","13_livstat","14_livstat","15_livstat","16_livstat","17_livstat","18_livstat","19_livstat","20_livstat","21_livstat","22_livstat","23_livstat","24_livstat","25_livstat","26_livstat"),c("1_livwhere","2_livwhere","3_livwhere","4_livwhere","5_livwhere","6_livwhere","7_livwhere","8_livwhere","9_livwhere","10_livwhere","11_livwhere","12_livwhere","13_livwhere","14_livwhere","15_livwhere","16_livwhere","17_livwhere","18_livwhere","19_livwhere","20_livwhere","21_livwhere","22_livwhere","23_livwhere","24_livwhere","25_livwhere","26_livwhere"),c("1_meet","2_meet","3_meet","4_meet","5_meet","6_meet","7_meet","8_meet","9_meet","10_meet","11_meet","12_meet","13_meet","14_meet","15_meet","16_meet","17_meet","18_meet","19_meet","20_meet","21_meet","22_meet","23_meet","24_meet","25_meet","26_meet"),c("1_tele","2_tele","3_tele","4_tele","5_tele","6_tele","7_tele","8_tele","9_tele","10_tele","11_tele","12_tele","13_tele","14_tele","15_tele","16_tele","17_tele","18_tele","19_tele","20_tele","21_tele","22_tele","23_tele","24_tele","25_tele","26_tele"))

print(x)
print(xx)

dt_03o_reshape <- reshape(tt, varying = x, direction = "long", timevar = "ID_i", idvar = c("ser_no","survey_year","qtype","adl_who_help") , v.names = c("relationship","sex","age","edu","work","marstat","livstat","livwhere","meet","tele"))

dt_03o_reshape[, "member_id":= list(paste0(qtype, "_", ser_no, "_", ID_i)),]
setcolorder(dt_03o_reshape, "member_id")

```


```{r}
# Reshape example : 
# ref: http://dwoll.de/rexrepos/posts/dfReshape.html
# note : I think reshape is more flexible than melt, therefore learn reshape is better.

Nj   <- 4
id   <- 1:Nj
t_11 <- round(rnorm(Nj,  8, 2), 2)
t_21 <- round(rnorm(Nj, 13, 2), 2)
t_31 <- round(rnorm(Nj, 13, 2), 2)
t_12 <- round(rnorm(Nj, 10, 2), 2)
t_22 <- round(rnorm(Nj, 15, 2), 2)
t_32 <- round(rnorm(Nj, 15, 2), 2)
dfW  <- data.frame(id, t_11, t_21, t_31, t_12, t_22, t_32)

# wide to long
dfL1 <- reshape(dfW, varying=list(c("t_11", "t_21", "t_31"),
                                   c("t_12", "t_22", "t_32")),
                 direction="long", timevar="IV1", idvar="id",
                 v.names=c("IV2-1", "IV2-2"))

dfL2 <- reshape(dfL1, varying=c("IV2-1", "IV2-2"),
                direction="long", timevar="IV2",
                idvar=c("id", "IV1"), v.names="DV")
head(dfL2)


# long to wide
dfW1 <- reshape(dfL2, v.names="DV", timevar="IV1",
                idvar=c("id", "IV2"), direction="wide")

dfW2 <- reshape(dfW1, v.names=c("DV.1", "DV.2", "DV.3"),
                timevar="IV2", idvar="id", direction="wide")

all.equal(dfW, dfW2, check.attributes=FALSE)
```






